const fieldErrors = {
  polices: {
    status: true,
    policy_number: true,
    branch_id: true,
    validity_start_date: true,
    validity_end_date: true,
    description_insured_property: true,
    insured_amount: true,
    currency: true,
    client_id: true,
    prime: true,
    isc: true,
    day_of_payment: true,
  },
  documents: {},
};

const headers = ["Nombre", "Fecha"];

const fieldsPages = {
  polices: {
    title: "Informacion de la poliza",
    fields: [
      {
        label: "Informacion principal de la poliza",
        name: "header",
        value: "",
        type: "header",
        mask: "",
        model: "insurances",
        display: ["create", "update"],
        col: 12,
      },

      {
        label: "Numero de Poliza",
        name: "policy_number",
        value: "",
        type: "number",
        mask: "",
        model: "polices",
        display: ["create", "update"],
        col: 4,
      },

      {
        label: "Estado",
        name: "status",
        value: [
          { label: "Vigente", value: "Vigente" },
          { label: "No Vigente", value: "No Vigente" },
        ],
        type: "select",
        mask: "",
        display: ["create", "update"],
        model: "polices",
        col: 4,
      },

      {
        label: "Fecha de Inicio",
        name: "validity_start_date",
        value: "",
        type: "date",
        mask: "",
        model: "polices",
        display: ["create", "update"],
        col: 4,
      },
      {
        label: "Fecha de Fin",
        name: "validity_end_date",
        value: "",
        type: "date",
        mask: "",
        model: "polices",
        display: ["create", "update"],
        col: 4,
      },
      {
        label: "Aseguradora",
        name: "insurances",
        value: [
          { label: "Vigente", value: "Vigente" },
          { label: "No Vigente", value: "No Vigente" },
        ],
        type: "select",
        mask: "",
        model: "polices",
        display: ["create", "update"],
        col: 4,
      },
      {
        label: "Ramo",
        name: "branch_id",
        value: [
          { label: "Vigente", value: "Vigente" },
          { label: "No Vigente", value: "No Vigente" },
        ],
        type: "branchButton",
        mask: "",
        model: "polices",
        display: ["create", "update"],
        col: 4,
      },

      {
        label: "Es Renovable?",
        name: "renewable",
        value: "",
        type: "checkbox",
        mask: "",
        model: "polices",
        display: ["create", "update"],
        col: 12,
      },
      {
        label: "Informacion prima y comisiones",
        name: "header",
        value: "",
        type: "header",
        mask: "",
        model: "polices",
        display: ["create", "update"],
        col: 12,
      },
      {
        label: "Monto de la Poliza",
        name: "insured_amount",
        value: "",
        type: "number",
        mask: "",
        model: "polices",
        display: ["create", "update"],
        col: 4,
      },
      {
        label: "Moneda",
        name: "currency",
        value: [
          { label: "RD", value: "DOP" },
          { label: "USD", value: "USD" },
        ],
        type: "select",
        mask: "",
        model: "polices",
        display: ["create", "update"],
        col: 4,
      },
      {
        label: "prime",
        name: "prime",
        value: "",
        type: "number",
        mask: "",
        model: "polices",
        display: ["create", "update"],
        col: 4,
      },
      {
        label: "isc",
        name: "isc",
        value: "",
        type: "number",
        mask: "",
        model: "polices",
        display: ["create", "update"],
        col: 4,
      },
      {
        label: "% de Comision del dueño",
        name: "commission_percentage_client_owner",
        value: "",
        type: "number",
        mask: "",
        model: "polices",
        display: ["create", "update"],
        col: 4,
      },
      {
        label: "% de Comision",
        name: "commission_percentage",
        value: "",
        type: "number",
        mask: "",
        model: "polices",
        display: ["create", "update"],
        col: 4,
      },
      {
        label: "Cliente",
        name: "client_id",
        value: [
          { label: "RD", value: "RD" },
          { label: "USD", value: "USD" },
        ],
        type: "select",
        mask: "",
        model: "polices",
        display: ["create", "update"],
        col: 4,
      },

      {
        label: "Dias de pago",
        name: "day_of_payment",
        value: "",
        type: "number",
        mask: "",
        model: "polices",
        display: ["create", "update"],
        col: 4,
      },
      {
        label: "Informacion del beneficiario",
        name: "header",
        value: "",
        type: "header",
        mask: "",
        model: "insurances",
        display: ["create", "update"],
        col: 12,
      },

      {
        label: "Descripcion de la asegurado?",
        name: "description_insured_property",
        value: "",
        type: "textarea",
        mask: "",
        model: "polices",
        display: ["create", "update"],
        col: 12,
      },
      {
        label: "Nombre del Beneficiario",
        name: "additional_beneficiary_name",
        value: "",
        type: "text",
        mask: "",
        model: "polices",
        display: ["create", "update"],
        col: 6,
      },
      {
        label: "Documento del Beneficiario",
        name: "additional_beneficiary_document",
        value: "",
        type: "text",
        mask: "",
        model: "polices",
        display: ["create", "update"],
        col: 6,
      },
      {
        label: "Comentario Privado",
        name: "protected_comment",
        value: "",
        type: "textarea",
        mask: "",
        model: "polices",
        display: ["create", "update"],
        col: 12,
      },
      {
        label: "Comentario Publico",
        name: "public_comment",
        value: "",
        type: "textarea",
        mask: "",
        model: "polices",
        display: ["create", "update"],
        col: 12,
      },
      {
        label: "",
        name: "espace",
        value: "",
        type: "br",
        mask: "",
        model: "insurances",
        display: ["create", "update"],
        col: 12,
      },

      {
        label: "",
        name: "espace",
        value: "",
        type: "br",
        mask: "",
        model: "insurances",
        display: ["create", "update"],
        col: 6,
      },
    ],
  },
  documents: {
    title: "Documentos adjuntos",
    rules: [],
    fields: [
      {
        label: "Subir todos los Adjuntos de la poliza",
        name: "documents",
        value: "",
        type: "file",
        child: {
          model: "polices",
          field: "policy_number",
          path: "polices",
        },
        display: ["create", "update"],
        model: "documents",
        mask: "",
        col: 12,
      },
      {
        label: "",
        name: "espace",
        value: "",
        type: "br",
        mask: "",
        model: "insurances",
        display: ["create", "update"],
        col: 6,
      },
    ],
  },
};

export { fieldErrors, headers, fieldsPages };
