const fieldErrors = {
  polices: {
    status: true,
    policy_number: true,
    branch_id: true,
    // validity_start_date: true,
    // validity_end_date: true,
    description_insured_property: true,
    insured_amount: true,
    currency: true,
    client_id: true,
    prime: true,
  },
  documents: {},
};

const headers = ["Nombre", "Fecha"];

const fieldsPages = {
  polices: {
    title: "Información de la póliza",
    rules: [
      {
        fieldFrom: "prime",
        valueFrom: "value_field",
        fieldTo: "isc",
        fieldResult: "neta",
        rule: "porcentage",
      },
    ],
    fields: [
      {
        label: "Información principal de la póliza",
        name: "header",
        value: "",
        type: "header",
        mask: "",
        model: "insurances",
        display: ["create", "update"],
        col: 12,
      },

      {
        label: "Número de Póliza",
        name: "policy_number",
        value: "",
        type: "text",
        mask: "",
        model: "polices",
        display: ["create", "update"],
        col: 12,
      },

      {
        label: "Estado",
        name: "status",
        value: [
          { label: "Vigente", value: "Vigente" },
          { label: "No Vigente", value: "No Vigente" },
        ],
        type: "select",
        mask: "",
        display: ["create", "update"],
        model: "polices",
        col: 4,
      },

      // {
      //   label: "Fecha de expedición",
      //   name: "validity_start_date",
      //   value: "",
      //   type: "date",
      //   mask: "",
      //   model: "polices",
      //   display: ["create", "update"],
      //   col: 4,
      // },
      // {
      //   label: "Fecha de vencimiento",
      //   name: "validity_end_date",
      //   value: "",
      //   type: "date",
      //   mask: "",
      //   model: "polices",
      //   display: ["create", "update"],
      //   col: 4,
      // },
      {
        label: "Aseguradora",
        name: "insurances",
        value: [
          { label: "Vigente", value: "Vigente" },
          { label: "No Vigente", value: "No Vigente" },
        ],
        type: "select",
        mask: "",
        model: "polices",
        display: ["create", "update"],
        col: 4,
      },
      {
        label: "Ramo",
        name: "branch_id",
        value: [
          { label: "Vigente", value: "Vigente" },
          { label: "No Vigente", value: "No Vigente" },
        ],
        type: "branchButton",
        mask: "",
        model: "polices",
        display: ["create", "update"],
        col: 4,
      },
      {
        label: "Descripción rápida de la propiedad/bien  asegurada",
        name: "description_insured_property",
        value: "",
        type: "textarea",
        mask: "",
        model: "polices",
        display: ["create", "update"],
        col: 12,
      },
      {
        label: "¿Es Renovable?",
        name: "renewable",
        value: "",
        type: "checkbox",
        mask: "",
        model: "polices",
        display: ["create", "update"],
        col: 6,
      },
      {
        label: "Información prima y comisiones",
        name: "header",
        value: "",
        type: "header",
        mask: "",
        model: "polices",
        display: ["create", "update"],
        col: 12,
      },
      {
        label: "Cliente",
        name: "client_id",
        value: [
          { label: "RD", value: "RD" },
          { label: "USD", value: "USD" },
        ],
        type: "select",
        mask: "",
        model: "polices",
        display: ["create", "update"],
        col: 4,
      },
      {
        label: "Valor Asegurado",
        name: "insured_amount",
        value: "",
        type: "number",
        mask: "",
        model: "polices",
        display: ["create", "update"],
        col: 4,
      },
      {
        label: "Moneda",
        name: "currency",
        value: [
          { label: "RD", value: "DOP" },
          { label: "USD", value: "USD" },
        ],
        type: "select",
        mask: "",
        model: "polices",
        display: ["create", "update"],
        col: 4,
      },
      {
        label: "prima",
        name: "prime",
        value: "",
        type: "number",
        mask: "",
        model: "polices",
        display: ["create", "update"],
        col: 6,
      },
      {
        label: "isc",
        name: "isc",
        value: "",
        type: "number",
        mask: "",
        model: "polices",
        display: ["create", "update"],
        col: 6,
      },
      {
        label: "Prima Neta",
        name: "neta",
        value: "",
        type: "number",
        mask: "",
        model: "polices",
        disabled:true,
        display: ["create", "update"],
        col: 4,
      },
      {
        label: "% de Comisión dueño del cliente",
        name: "commission_percentage_client_owner",
        value: "",
        type: "number",
        mask: "",
        model: "polices",
        disabled:true,
        display: ["create", "update"],
        col: 4,
      },
      {
        label: "% de comisión compañía",
        name: "commission_percentage",
        value: "",
        type: "number",
        mask: "",
        model: "polices",
        disabled:true,
        display: ["create", "update"],
        col: 4,
      },


      {
        label: "Información del beneficiario adicional",
        name: "header",
        value: "",
        type: "header",
        mask: "",
        model: "insurances",
        display: ["create", "update"],
        col: 12,
      },

      {
        label: "Nombre del beneficiario adicional",
        name: "additional_beneficiary_name",
        value: "",
        type: "text",
        mask: "",
        model: "polices",
        display: ["create", "update"],
        col: 6,
      },
      {
        label: "No. Documento del Beneficiario adicional",
        name: "additional_beneficiary_document",
        value: "",
        type: "text",
        mask: "",
        model: "polices",
        display: ["create", "update"],
        col: 6,
      },
      {
        label: "Comentario Privado",
        name: "protected_comment",
        value: "",
        type: "textarea",
        mask: "",
        model: "polices",
        display: ["create", "update"],
        col: 12,
      },
      {
        label: "Comentario Público",
        name: "public_comment",
        value: "",
        type: "textarea",
        mask: "",
        model: "polices",
        display: ["create", "update"],
        col: 12,
      },
      {
        label: "",
        name: "espace",
        value: "",
        type: "br",
        mask: "",
        model: "insurances",
        display: ["create", "update"],
        col: 12,
      },

      {
        label: "",
        name: "espace",
        value: "",
        type: "br",
        mask: "",
        model: "insurances",
        display: ["create", "update"],
        col: 6,
      },
    ],
  },
  documents: {
    title: "Documentos adjuntos",
    rules: [],
    fields: [
      {
        label: "Subir todos los Adjuntos de la póliza",
        name: "documents",
        value: "",
        type: "file",
        child: {
          model: "polices",
          field: "policy_number",
          path: "polices",
        },
        display: ["create", "update"],
        model: "documents",
        mask: "",
        col: 12,
      },
      {
        label: "",
        name: "espace",
        value: "",
        type: "br",
        mask: "",
        model: "insurances",
        display: ["create", "update"],
        col: 6,
      },
    ],
  },
};

export { fieldErrors, headers, fieldsPages };
